### ISSUE TITLE
Validitor returning false for valid is weird

### ISSUE THREAD

**Issue by k88hudson** [k88hudson/react-formation#15]
Maybe we should return `true` instead and check for `=== true` instead?

**Comment by pippinlee** [comment]
Initial feelings when dealing with valid/invalid options while updating `Validator.test.js` totally agree with this. We now have the `valid` and `invalid` keys in there to help make this a bit clearer.

If I'm reading this correctly -- looks like `Validator.prototype.assert` in `Validator.js` can be updated to make it so that we're returning `true` like you've mentioned above.

[https://github.com/k88hudson/react-formation/blob/master/src/lib/Validator.js#L154](https://github.com/k88hudson/react-formation/blob/master/src/lib/Validator.js#L154)

Looks like we'll also need to update `CreateFormMixin.js` per current API docs:

[https://github.com/k88hudson/react-formation/blob/master/src/lib/apiDocs/submitGroup.md](https://github.com/k88hudson/react-formation/blob/master/src/lib/apiDocs/submitGroup.md)
